blockExoticSubdeps: true
minimumReleaseAgeExcludePrune: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 10080
enablePrePostScripts: false
shellEmulator: true
verifyDepsBeforeRun: install
optimisticRepeatInstall: true

allowBuilds:
  esbuild: true
